repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.12
    hooks:
      - id: terragrunt-hclfmt
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-merge-conflict
      - id: no-commit-to-branch
        always_run: false
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_tflint
        args:
          - 'args=--deep'
          - 'args=--enable-rule=terraform_documented_variables'
          - 'args=--module'
      - id: terraform_tfsec
        exclude: '^examples'
      - id: terraform_validate
        exclude: '^examples'
        args: ['--envs=AWS_DEFAULT_REGION="us-east-1"']
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.14.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
