[severity]
level = "HIGH"
[rules]
    skip-rules = [
        "AWS.S3Bucket.EncryptionandKeyManagement.High.0405",
        "AWS.S3Bucket.IAM.High.0370",
        "AWS.AKK.DP.HIGH.0012",
        "AWS.AKK.DP.HIGH.0013"
    ]